batch_size: 1
ctc_type: CMU_ctl
ctc_weight: 0.2
data_path: ../data/netflix_whole/
dataset: netflix_whole
decay_factor: 0.3
dropout_rate: 0.135883
duration: 20
early_stopping_patience: 10
epochs: 1000
gpus: 1
gradient_clip_val: 100
hop_size: 512
input_features: mel
kernal_size: 3
learning_rate: 0.001
load_pretrain: null
model_name: crnn
n_blocks: 8
n_class: 2
n_features: 128
n_fft: 1024
n_hidden: 64
n_sample: 10
n_stacks: 2
num_workers: 4
patience: 2
pool_size: 2
rnn_layers: 1
save_path: logger/default/version_28
seed: 42
sr: 16000
threshold_m: 0.5
threshold_s: 0.5
use_ctc: false
use_pcen: true
weight_decay: 0.0001
